config/routes.rb
Rails.application.routes.draw do
  resources :tasks, except: [:index] do
    resources :complete, only: [:create]

    collection do
      resources :complete_all, only: [:create]
      resources :clear_complete, only: [:create]
    end
  end
  resources :active, only: [:index]
  resources :completed, only: [:index]
  root to: 'tasks#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  after_create_commit :prepend_task
  after_update_commit :replace_task
  after_destroy_commit :remove_task

  scope :complete, ->{ where(complete: true) }
  scope :incomplete, ->{ where(complete: false) }

  def self.all_complete?
    Task.count > 0 && self.incomplete.count == 0
  end

  def uncomplete!
    update!(complete: false)
  end

  def complete!
    update!(complete: true)
  end

  private

  def prepend_task
    broadcast_prepend_to :tasks_list_all
    broadcast_prepend_to :tasks_list_active
    replace_clear_complete
    replace_complete_all_tasks
    replace_items_left
  end

  def replace_task
    broadcast_replace_to :tasks_list_all

    if complete?
      broadcast_prepend_to :tasks_list_complete
    else
      broadcast_prepend_to :tasks_list_active
    end

    replace_clear_complete
    replace_complete_all_tasks
    replace_items_left
  end

  def remove_task
    broadcast_remove_to :tasks_list_all
    broadcast_remove_to :tasks_list_active
    broadcast_remove_to :tasks_list_complete
    replace_clear_complete
    replace_complete_all_tasks
    replace_items_left
  end

  def replace_complete_all_tasks
    Turbo::StreamsChannel.broadcast_replace_to :tasks, target: "complete_all_tasks", partial: 'tasks/complete_all', locals: { all_complete: Task.all_complete? }
  end

  def replace_items_left
    Turbo::StreamsChannel.broadcast_replace_to :tasks, target: "items_left", partial: 'tasks/items_left', locals: { incomplete_items_count: Task.incomplete.count }
  end

  def replace_clear_complete
    Turbo::StreamsChannel.broadcast_replace_to :tasks, target: "clear_complete", partial: 'tasks/clear_complete', locals: { complete_count: Task.complete.count }
  end
end

app/controllers/active_controller.rb
class ActiveController < ApplicationController
  def index
    @tasks = Task.incomplete.order(created_at: :desc)
    @all_complete = Task.all_complete?
    @incomplete_items_count = Task.incomplete.count
    @complete_count = Task.complete.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clear_complete_controller.rb
class ClearCompleteController < ApplicationController
  def create
    Task.complete.destroy_all
    redirect_to root_url
  end
end

app/controllers/complete_all_controller.rb
class CompleteAllController < ApplicationController
  def create
    if params[:mark_incomplete] == "true"
      Task.complete.each(&:uncomplete!)
    else
      Task.incomplete.each(&:complete!)
    end

    redirect_to root_url
  end
end

app/controllers/complete_controller.rb
class CompleteController < ApplicationController
  before_action :set_task

  def create
    @task.update!(task_params)

    redirect_to @task
  end

  private

  def task_params
    p = params.require(:task).permit(:complete)

    if p.has_key?(:complete)
      p[:complete] = p[:complete] == "1"
    end

    p
  end

  def set_task
    @task = Task.find(params[:task_id])
  end
end

app/controllers/completed_controller.rb
class CompletedController < ApplicationController
  def index
    @tasks = Task.complete.order(created_at: :desc)
    @all_complete = Task.all_complete?
    @incomplete_items_count = Task.incomplete.count
    @complete_count = Task.complete.count
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all.order(created_at: :desc)
    @all_complete = Task.all_complete?
    @incomplete_items_count = Task.incomplete.count
    @complete_count = Task.complete.count
  end

  def show
    @all_complete = Task.all_complete?
  end

  def create
    @task = Task.create!(task_params)

    redirect_to root_url
  end

  def edit
  end

  def update
    @task.update!(task_params)

    redirect_to @task
  end

  def destroy
    @task.destroy!
  end

  private

  def task_params
    params.require(:task).permit(:body)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/active/index.html.erb
<%= render partial: "tasks/list", locals: { stream_name: "tasks_list_active", tasks: @tasks, all_complete: @all_complete, incomplete_items_count: @incomplete_items_count, complete_count: @complete_count } %>

app/views/completed/index.html.erb
<%= render partial: "tasks/list", locals: { stream_name: "tasks_list_complete", tasks: @tasks, all_complete: @all_complete, incomplete_items_count: @incomplete_items_count, complete_count: @complete_count } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>

    <footer class="info">
      <p>Double-click to edit a todo</p>
      <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
      <p>See an example of the functionality in the <a href="https://todomvc.com/examples/backbone/#/" target="_blank">Backbone.js</a> example.</p>
    </footer>
  </body>
</html>

app/views/tasks/_clear_complete.html.erb
<%= turbo_frame_tag "clear_complete" do %>
  <% if complete_count > 0 %>
    <%= button_to clear_complete_index_path, method: :post, class: "clear-completed" do %>
      Clear completed
    <% end %>
  <% end %>
<% end %>

app/views/tasks/_complete_all.html.erb
<%= turbo_frame_tag "complete_all_tasks" do %>
  <%= button_to complete_all_index_path(mark_incomplete: all_complete), method: :post, class: "toggle-all #{all_complete ? 'all-complete' : ''}" do %>
  <% end %>
<% end %>

app/views/tasks/_edit_form.html.erb
<%= turbo_frame_tag dom_id(task) do %>
  <li class="editing">
    <%= form_with model: task do |f| %>
      <%= f.text_field :body, class: 'edit', autofocus: true %>
    <% end %>
  </li>
<% end %>

app/views/tasks/_form.html.erb
<%= turbo_frame_tag dom_id(Task.new) do %>
  <%= form_with model: Task.new do |f| %>
    <%= f.text_field :body, class: "new-todo", placeholder: "What needs to be done?", autofocus: true %>
  <% end %>
<% end %>

app/views/tasks/_items_left.html.erb
<%= turbo_frame_tag "items_left" do %>
  <span class="todo-count">
    <strong><%= incomplete_items_count %></strong> items left
  </span>
<% end %>

app/views/tasks/_list.html.erb
<section class="todoapp">
  <header class="header">
    <h1>todos</h1>
    <%= render partial: "tasks/form" %>
  </header>
  <section class="main" style="display: block;">
    <%= turbo_stream_from :tasks %>
    <%= turbo_stream_from stream_name %>
    <%= render partial: "tasks/complete_all", locals: { all_complete: all_complete } %>
    <ul class="todo-list">
      <%= turbo_frame_tag "tasks" do %>
        <%= render tasks %>
        <li class="completed">
          <div class="view">
            <input class="toggle" type="checkbox" checked="">
            <label>These are just samples!!!</label>
            <button class="destroy"></button>
          </div>
          <input class="edit" value="asdfasdf">
        </li>
      <% end %>
    </ul>
  </section>
  <footer class="footer" style="display: block;">
    <%= render partial: 'tasks/items_left', locals: { incomplete_items_count: incomplete_items_count } %>
    <ul class="filters">
      <li>
        <%= link_to "All", root_path, class: "#{stream_name == "tasks_list_all" ? 'selected' : ''}" %>
      </li>
      <li>
        <%= link_to "Active", active_index_path, class: "#{stream_name == "tasks_list_active" ? 'selected' : ''}" %>
      </li>
      <li>
        <%= link_to "Completed", completed_index_path, class: "#{stream_name == "tasks_list_complete" ? 'selected' : ''}" %>
      </li>
    </ul>

    <%= render partial: "tasks/clear_complete", locals: { complete_count: complete_count } %>
  </footer>
</section>

app/views/tasks/_task.html.erb
<%= turbo_frame_tag dom_id(task) do %>
  <li class="<%= task.complete? ? 'completed' : 'view' %>">
    <%= form_with method: :get, url: edit_task_path(task), id: "edit_form_#{dom_id(task)}" do |f| %>
    <% end %>
    <div class="view" ondblclick="document.getElementById('<%= "edit_form_#{dom_id(task)}" %>').requestSubmit();">
      <%= button_to task_complete_index_path(task, task: { complete: task.complete? ? '0' : '1' }), method: :post, form_class: "toggle #{task.complete? ? 'complete' : ''}" do %><% end %>
      <label><%= task.body %></label>
      <%= button_to task_path(task), method: :delete, class: "destroy" do %><% end %>
    </div>
  </li>
<% end %>

app/views/tasks/edit.html.erb
<%= render partial: "tasks/edit_form", locals: { task: @task } %>
<%#= turbo_stream.replace dom_id(@task), partial: "tasks/edit_form", locals: { task: @task } %>

app/views/tasks/index.html.erb
<%= render partial: "tasks/list", locals: { stream_name: "tasks_list_all", tasks: @tasks, all_complete: @all_complete, incomplete_items_count: @incomplete_items_count, complete_count: @complete_count } %>

app/views/tasks/show.html.erb
<%= render @task %>